# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-19 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basemodel',
            name='gender',
            field=models.CharField(choices=[('UNSPECIFIED', 'SSML_VOICE_GENDER_UNSPECIFIED'), ('MALE', 'MALE'), ('FEMALE', 'FEMALE'), ('NEUTRAL', 'NEUTRAL')], default='', max_length=100),
        ),
        migrations.AddField(
            model_name='basemodel',
            name='pitch',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='basemodel',
            name='speed',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='basemodel',
            name='voice_type',
            field=models.CharField(choices=[('Standard', 'Standard'), ('WaveNet', 'WaveNet')], default='', max_length=100),
        ),
    ]
