# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-06-20 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180620_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemodel',
            name='pitch',
            field=models.IntegerField(choices=[('0.25', '0.25'), ('0.50', '0.50'), ('0.75', '0.75'), ('1', '1'), ('1.25', '1.25'), ('1.50', '1.50'), ('1.75', '1.55'), ('2', '2'), ('2.25', '2.25'), ('2.50', '2.50'), ('2.45', '2.75'), ('3', '3'), ('3.25', '3.25'), ('3.50', '3.50'), ('3.75', '3.75'), ('4', '4')], default='', max_length=100),
        ),
    ]
